services:
  db:
    container_name: postgres
    build: .
    restart: always
    environment:
        POSTGRES_USER: pguser
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: