services:
  # web:
  #   restart: always
  #   depends_on:
  #     - db
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   networks:
  #     - backend
  db:
    build: ./db
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: