# # GET  http://localhost:8000/api/activate/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.sU30l9m_tmqh_HzL9lvvy7nv7g-9Q18sxtRwMMslpQA
# # Content-Type: application/json
# # {}

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    # "first_name":"flirsts_name",
    # "last_name":"firsmt_sname",
    "email":"dijad7190@esterace.com",
    "password":"aoutifra1"
    # "password1":"aoutifra1"
}

#############

# GET http://127.0.0.1:8000/api/user_info
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1ODc5MzgwLCJpYXQiOjE3MjU4NzkwODAsImp0aSI6IjQ4NjI1ZjQ3Yjg3ZTQzM2ZhMzMzYjRmZDdhYjFlODU0IiwidXNlcl9pZCI6MX0.XpJJvhaJWEqqE4fq1NcRBo2s-qJ9_glcv3ZRCNgoUxI
# Content-Type: application/json

# {
#     # "first_name":"flirsts_name",
#     # "last_name":"firsmt_sname",
#     "email":"dijad7190@esterace.com"
#     # "password":"aoutifra1"
#     # "password1":"aoutifra1"
# }


# POST https://api.intra.42.fr/oauth/token
# Content-Type: application/json

# {
#     "grant_type": "authorization_code",
#     "client_id": "u-s4t2ud-b7a07e95a71b24423b13ff59e31449be4182b63b7aaf9bc87dcd54d2be5e83ec",
#     "client_secret": "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",
#     "code": "09ea9d8d67a68a778dc4b49fad2d85be30020f2e0161a967ad8f1446cd2c2d22",
#     "redirect_uri": "http://127.0.0.1:8000/api/callback"
# }

### Sign Up Request
# GET   https://api.intra.42.fr/v2/me
###

POST http://127.0.0.1:8000/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1ODgyMDE3LCJpYXQiOjE3MjU4ODE3MTcsImp0aSI6IjA2M2YyMTQ1MTY0MDRkYTliYzEzNzI2MzYxMmU5OWEyIiwidXNlcl9pZCI6MX0.nZwMjRJK8fWMBNZfa2mjaYhgo5CoV4xd5BeMq6AWZRU
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNTk2ODExNywiaWF0IjoxNzI1ODgxNzE3LCJqdGkiOiI0OTM2NDBmOWFkODM0N2E1ODgwOTZkOTIwNTI4MjIzMiIsInVzZXJfaWQiOjF9.Ms1Y-dK4CjfPg0eTvnjO6Z2FzdTIC9Zv6VtW6X8QFoA"
}
