# # GET  http://localhost:8000/api/activate/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.sU30l9m_tmqh_HzL9lvvy7nv7g-9Q18sxtRwMMslpQA
# # Content-Type: application/json
# # {}

GET http://127.0.0.1:8000/api/user_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4ODE0MzQ2LCJpYXQiOjE3Mjg4MTQwNDYsImp0aSI6ImM1NTA2NjljOWEzMzRkMTliNDU3MmJmZmY5MmFjNzFhIiwidXNlcl9pZCI6OH0.RSPE9kuY2SbGeH0Pzr0sK_91P1rvcXutA6DcZcCncZ8

{

}


##############
##############
##############
##############
##############
##############
##############
##############


POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
  "username":"",
  "email":"sifi6s0ss27@gmail.com",
  "password":"aoutifra1",
  "first_name":"dijad",
  "last_name":"dijad"
}