# Generated by Django 5.0.6 on 2024-06-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='avatar',
            field=models.CharField(default='.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='bio',
            field=models.CharField(default='write somthing nice here', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
