# Generated by Django 4.2.14 on 2024-07-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='is_active',
        ),
    ]
