# Generated by Django 4.2.14 on 2024-07-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_user_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
