# Generated by Django 5.0.6 on 2024-06-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_user_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.CharField(default='img url', max_length=255),
        ),
    ]
