# Generated by Django 4.2.14 on 2024-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
