# Generated by Django 5.0.6 on 2024-06-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
