# Generated by Django 4.2.16 on 2024-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_user_profile_groups_user_profile_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='is2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='pyotp_secret',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
