# Generated by Django 4.2.14 on 2024-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_user_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
