# Generated by Django 4.2.16 on 2024-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_profile_created_at_user_profile_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
