# Generated by Django 4.2.16 on 2024-10-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_profile_matches_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
