# Generated by Django 4.2.16 on 2024-10-19 16:39

import django.core.validators
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_profile_matches_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', validators=[profiles.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='First name must be at least 2 characters long and contain only letters', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='First name must be at least 2 characters long and contain only letters', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='username must be at least 2 characters long and contain only letters and numbers and underscores', regex='^(?=.*[a-zA-Z])[a-zA-Z0-9_]*$')]),
        ),
        migrations.AlterModelTable(
            name='user_profile',
            table='User_profile',
        ),
    ]
