# Generated by Django 4.2.14 on 2024-07-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='username',
        ),
    ]
