# Generated by Django 4.2.16 on 2024-10-15 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_user_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(['^[0-9]*$'], 'Only alphanumeric characters are allowed.')]),
        ),
    ]
