# Generated by Django 4.2.13 on 2024-07-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_user_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user_permissions',
        ),
    ]
