# Generated by Django 4.2.16 on 2024-10-15 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_user_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^[0-9]*$')]),
        ),
    ]
