# Generated by Django 4.2.16 on 2024-10-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_user_profile_is_verified_and_more'),
        ('profiles', '0011_alter_user_profile_first_name'),
    ]

    operations = [
    ]
